// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXASTAwWupbB8_Lyi_92pi_VPbYfdKmD4',
    appId: '1:922708522833:web:3c964bc99e9af7a61a8570',
    messagingSenderId: '922708522833',
    projectId: 'confidex-sondos-2026',
    authDomain: 'confidex-sondos-2026.firebaseapp.com',
    storageBucket: 'confidex-sondos-2026.firebasestorage.app',
    measurementId: 'G-GZ4WCW4C62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb_J1rPSyLmY6Xx_aq7wX7j8TANLZ-RuM',
    appId: '1:922708522833:android:e2bcd13c417b01ab1a8570',
    messagingSenderId: '922708522833',
    projectId: 'confidex-sondos-2026',
    storageBucket: 'confidex-sondos-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUfgjN-qdY389H1Cmj-7lTTit1AuVqkmE',
    appId: '1:922708522833:ios:98a50aa1980c76bc1a8570',
    messagingSenderId: '922708522833',
    projectId: 'confidex-sondos-2026',
    storageBucket: 'confidex-sondos-2026.firebasestorage.app',
    iosBundleId: 'com.example.confidexApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUfgjN-qdY389H1Cmj-7lTTit1AuVqkmE',
    appId: '1:922708522833:ios:98a50aa1980c76bc1a8570',
    messagingSenderId: '922708522833',
    projectId: 'confidex-sondos-2026',
    storageBucket: 'confidex-sondos-2026.firebasestorage.app',
    iosBundleId: 'com.example.confidexApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXASTAwWupbB8_Lyi_92pi_VPbYfdKmD4',
    appId: '1:922708522833:web:30571a45a7e6735b1a8570',
    messagingSenderId: '922708522833',
    projectId: 'confidex-sondos-2026',
    authDomain: 'confidex-sondos-2026.firebaseapp.com',
    storageBucket: 'confidex-sondos-2026.firebasestorage.app',
    measurementId: 'G-7XCQE248T7',
  );
}
